#!/usr/bin/env bash
#
# Wifi-Cracker01 / WiFi Audit GUI - one-command installer for Kali & Debian.
#
#   curl -fsSL https://raw.githubusercontent.com/AliSalih-ops/Wifi-Cracker01/main/install.sh | sudo bash
#
# Installs the system tools it drives, clones the app to /opt, and drops a
# `wifi-audit` command on your PATH plus an app-menu entry. Safe to re-run
# (it just updates to the latest version).
#
set -euo pipefail

REPO_URL="${WIFI_AUDIT_REPO:-https://github.com/AliSalih-ops/Wifi-Cracker01.git}"
BRANCH="${WIFI_AUDIT_BRANCH:-main}"
PREFIX="/opt/wifi-cracker01"
LAUNCHER="/usr/local/bin/wifi-audit"
DESKTOP="/usr/share/applications/wifi-audit.desktop"

say() { printf '\033[1;36m[wifi-audit]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[wifi-audit]\033[0m %s\n' "$*" >&2; }

# Re-run ourselves as root if needed (preserving env for the sudo prompt).
if [ "$(id -u)" -ne 0 ]; then
  say "Root is required to install packages; elevating with sudo..."
  exec sudo -E bash "$0" "$@"
fi

if ! command -v apt-get >/dev/null 2>&1; then
  err "This installer targets Debian/Kali (apt). See the README for manual setup on other distros."
  exit 1
fi

say "Installing core dependencies..."
apt-get update -y
apt-get install -y python3 python3-tk git aircrack-ng iw iproute2

say "Installing optional tools (PMKID capture + MAC spoofing)..."
apt-get install -y hcxtools hcxdumptool macchanger \
  || say "Some optional tools weren't available; PMKID/MAC features may be limited."

say "Fetching the app into $PREFIX ..."
if [ -d "$PREFIX/.git" ]; then
  git -C "$PREFIX" fetch --depth 1 origin "$BRANCH"
  git -C "$PREFIX" reset --hard "origin/$BRANCH"
else
  rm -rf "$PREFIX"
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$PREFIX"
fi

say "Installing launcher -> $LAUNCHER"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Wifi-Cracker01 launcher (generated by install.sh). Re-execs as root for radio work.
DIR="$PREFIX"
needs_root=1
for a in "\$@"; do case "\$a" in --demo|--selftest|--version|-h|--help) needs_root=0 ;; esac; done
if [ "\$needs_root" -eq 1 ] && [ "\$(id -u)" -ne 0 ]; then
  exec sudo -E "\$0" "\$@"
fi
cd "\$DIR" || { echo "Install dir \$DIR is missing; re-run install.sh"; exit 1; }
exec python3 -m wifiaudit "\$@"
EOF
chmod +x "$LAUNCHER"

if [ -f "$PREFIX/wifi-audit.desktop" ]; then
  say "Installing app-menu entry -> $DESKTOP"
  cp "$PREFIX/wifi-audit.desktop" "$DESKTOP"
  chmod 644 "$DESKTOP"
  update-desktop-database >/dev/null 2>&1 || true
fi

say "Verifying with the offline self-test..."
if ( cd "$PREFIX" && python3 -m wifiaudit --selftest >/dev/null 2>&1 ); then
  say "Self-test passed."
else
  err "Self-test reported issues - the app still installed; run 'wifi-audit --selftest' to see details."
fi

cat <<EOF

$(say "Installed.")
  Launch the GUI:      wifi-audit
  Preview (no radio):  wifi-audit --demo
  Update later:        re-run this installer, or 'wifi-audit' will use /opt/wifi-cracker01
  Uninstall:           sudo bash $PREFIX/uninstall.sh

Use only against networks you are authorized to test.
EOF
